name = "Team Gecko"
license = "UNLICENSED"
licenselink = "https://github.com/Goldfish-Intelligence/team-gecko.de/blob/master/LICENSE"
description = "Theme for team-gecko.de"
homepage = "https://team-gecko.de/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Tim Domnick"
