baseURL = 'https://team-gecko.de/'
languageCode = 'de-de'
disableKinds = ["taxonomy", "RSS", "term"]
title = 'Team Gecko'

[privacy]
    [privacy.youtube]
        privacyEnhanced = true

[markup.goldmark.renderer]
unsafe = true
